jobs:
  Deploy:
    environment:
      AWS_DEFAULT_REGION: 'eu-west-1'
    executor: aws-serverless/default
    steps:
      - aws-serverless/install
      - checkout
      - run: yarn
      - run: CI=false yarn build
      - run: CI=false yarn export
      - run: sam deploy --s3-bucket sam-jonsmedia --stack-name jontarrant --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset
      - run: aws s3 sync ./out s3://jontarrant.me
      
orbs:
  aws-serverless: circleci/aws-sam-serverless@2.0.0
  node: circleci/node@2.0.2
version: 2.1
workflows:
  FullFlow:
    jobs:
      - Deploy